#[Backend]
backend = "auto"
transition_mode = "static"

#[Smoothing]
smoothing = true
startup_duration = 0.5
shutdown_duration = 0.5
adaptive_interval = 1

#[Static configuration]
static_temp = 6500 # Accurate colors
static_gamma = 115 # Slightly boosted brightness
